version: "3.8"

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cars_db
      - DB_USER=cars_user
      - DB_PASSWORD=cars_password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cars_db
      - POSTGRES_USER=cars_user
      - POSTGRES_PASSWORD=cars_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cars_user -d cars_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
